name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 20 #Vocareum runs on 14
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Download JUnit
        run: |
          mkdir lib
          curl -L -o lib/junit-4.13.1.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13.1/junit-4.13.1.jar

      - name: Compile Java code with JUnit
        run: |
          javac -cp ./src:lib/* $(find . -name "*.java")

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Download JUnit
        run: |
          mkdir lib
          curl -L -o lib/junit-4.13.1.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13.1/junit-4.13.1.jar
          curl -L -o lib/hamcrest-core-1.3.jar https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

      - name: Compile Java code with JUnit
        run: |
          javac -cp ./src:lib/* $(find . -name "*.java")

      - name: Run JUnit tests
        run: |
          java -cp ./src:lib/* org.junit.runner.JUnitCore DatabaseTest NetworkTest